# Sasha Agent Configuration
# Fill in your actual API keys and tokens below. Do NOT commit this file to public repos.

# --- API Key Management ---
# DO NOT store real API keys in this file.
# Use environment variables or a .env file for all secrets.
# To rotate or update keys:
#   1. Delete the old key from your environment or secret manager.
#   2. Add the new key as an environment variable (e.g., $env:GOOGLE_API_KEY or $env:HUGGINGFACE_API_KEY).
#   3. Restart the backend server.
#   4. Never commit real keys to version control.
#
# Example (PowerShell):
#   $env:GOOGLE_API_KEY = "your_new_google_api_key"
#   $env:HUGGINGFACE_API_KEY = "your_new_huggingface_api_key"
#
# For production, use a secure secret manager (GCP Secret Manager, AWS Secrets Manager, etc.)

# --- Service Configurations ---
discord:
  bot_token: ""
  guild_id: ""
  channel_id: ""

gcp:
  project_id: ""
  service_account_json: ""

google:
  api_key: ""  # Do not store real keys here

huggingface:
  api_key: ""  # Do not store real keys here 